### ISSUE TITLE
add option to restart process on file change

### ISSUE THREAD

**Issue by rprtr258** [rprtr258/pm#23]
`watch` config directive should contain list of
- files
- directories
- globs(?)
- regexes(?)
to watch, and if they are changed, restart the process

implementation examples:
https://github.com/fsnotify/fsnotify
https://github.com/cortesi/modd
https://github.com/eradman/entr
https://github.com/cespare/reflex
https://github.com/cosmtrek/air

maybe not needed since above programs can handle that themselves?

**Comment by Satont** [comment]
> maybe not needed since above programs can handle that themselves?

Needed.

**Comment by rprtr258** [comment]
watch is implemented in v0.0.2 (not yet released) with `--watch` flag and `watch` regex config, ignoring `.git` directories inside shim, since we stole batched file watcher from cue in which ignoring `.git` doesn't work for some reason
